### ISSUE TITLE
TypeError using pandas.Timestamp as index

### ISSUE THREAD

**Issue by Stigjb** [stringertheory/traces#144]
The following snippet yields a `TypeError: Cannot compare type 'Timestamp' with type 'Infinity'`:

```python
import pandas as pd
import traces
ts = traces.TimeSeries()
ts[pd.Timestamp('2017-07-20 12:44')] = 1
```

traces version 0.3.1

**Comment by stringertheory** [comment]
Thanks @Stigjb! This no longer raises an error — not sure if it's because of updates in `infinity`or `pandas` over the last handful of years, but closing for now.
