### ISSUE TITLE
TimeSeries._get_linear_interpolate() explicitly casts int to float

### ISSUE THREAD

**Issue by onurmatik** [stringertheory/traces#236]
TimeSeries._get_linear_interpolate() explicitly casts int to float as per this line:

https://github.com/datascopeanalytics/traces/blob/c15ed57b162f2a72ec28c6589976ca4c7742f0f1/traces/timeseries.py#L101

This causes inconsistency as int goes in, float comes out. What is the purpose of this?

**Comment by multibour** [comment]
Moreover, this causes the library to have no support for linear interpolation with numpy arrays or any other object that supports arithmetic operations

**Comment by stringertheory** [comment]
Thanks for the note! This is left over from python 2 when the default was integer division. Just removed explicit casts to float.
